### PR TITLE
Damageevent fix

### PR DESCRIPTION
**Pull request by 00100000**
Done without math so far (make Tristan do that he's the math nerd). Please review my code, as I'm not sure if I did it right. It gets the player's armor pieces separately and checks their types. I know it's kinda a brute force implementation, but we can always patch it up a bit later.

### CODE REVIEW

**Comment by 01-1** [comment]
U used helmet.getType() on all of them lol

**Comment by 01-1** [comment]
wait this might be useless

**Comment by 00100000** [comment]
@Zyxok wait, if you got all a player's armor as an itemstack, do positions 0-3 correspond to Helmet, Chestplate, Leggings, and Boots? Because if so, I realized I could probably check for armor material types but I'm not too sure about how ItemStack armor works.

**Comment by 01-1** [comment]
No. It is different, backwards i think but search it up. and maybe test it to see

Sent from my iPhone

On Jan 13, 2020, at 19:17, 00100000 <notifications@github.com> wrote:

﻿

@Zyxok<https://github.com/Zyxok> wait, if you got all a player's armor as an itemstack, do positions 0-3 correspond to Helmet, Chestplate, Leggings, and Boots? Because if so, I realized I could probably check for armor material types but I'm not too sure about how ItemStack armor works.

**Pull request closed without merging**
